global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "news-feed-ui"
    metrics_path: "/metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:8180"]
  - job_name: "news-collector"
    metrics_path: "/metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:8761"]
  - job_name: "news-analyzer"
    metrics_path: "/metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:8081"]
  - job_name: "prometheus"
    metrics_path: "/metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]