name: Deploy Collector App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "daily-news-collector" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            PORT
            APP
        env:
          HD_PORT: 8761
          HD_APP: applications/data-collector-server/build/libs/data-collector-server-1.0-SNAPSHOT.jar